### ISSUE TITLE
i can't download plugin

### ISSUE THREAD

**Issue by tangshengzhi** [debuggap/vide#3]
When I download the vide-plugin-debug-webview  always suggest I need to download  npm or cnpm first ,even if I have download it(my computer is macbook air)

**Comment by vicwang163** [comment]
@tangshengzhi could you attach the screenshot that the error occurs ,tks

**Comment by ztommy** [comment]
same issue. look here: https://wx3.sinaimg.cn/mw690/5dc6f774gy1flti2510fsj21740h8whg.jpg

**Comment by vicwang163** [comment]
for the latest version, the ide will display the entire error message when failing to install plugin
